config/routes.rb
EasilyxMovie::Application.routes.draw do
  match '/cover', to: 'cover#cover'

  match '/validate', to: 'static_pages#validate'
  match '/showtimes', to: 'static_pages#showtimes'
  match '/checklogin', to: 'checklogin#checklogin'
  match '/showmovie', to: 'static_pages#showmovie'
  match '/showtheatre', to: 'static_pages#showtheatre'
  match '/preferences', to: 'static_pages#preferences'
  match '/boxoffice', to: 'static_pages#boxoffice'
  match '/news', to: 'static_pages#news'
  match '/reviews', to: 'static_pages#reviews'
  match '/showreview', to: 'static_pages#showreview'
  match '/confirm_account', to: 'static_pages#confirm_account'
  match '/forgot_password', to: 'static_pages#forgot_password'
  match '/reset_password', to: 'static_pages#reset_password'
  match '/trailers', to: 'static_pages#trailers'
  match '/contact', to: 'static_pages#contact'
  match '/aboutus', to: 'static_pages#aboutus'
  match '/idevice', to: 'static_pages#idevice'
    match '/search', to: 'static_pages#search'
match '/auth/:provider/callback', to: 'static_pages#facebook'
    match '/link_fb', to: 'static_pages#link_fb'
        match '/unlink_fb', to: 'static_pages#unlink_fb'

match '/share', to: 'static_pages#share'

  match '/signin', to: 'static_pages#signin'

  match '/register', to: 'static_pages#register'

  match '/movies', to: 'static_pages#movies'

  match '/theatres', to: 'static_pages#theatres'

  match '/settings', to: 'static_pages#settings'

  match '/buddies', to: 'static_pages#buddies'
  match '/signout', to: 'static_pages#signout'

  match '/home', to: 'static_pages#home'
  match '/edit', to: 'static_pages#edit'
  resources :static_pages

  root to: 'static_pages#movies'

end

app/views/layouts/_footer.html.erb
<footer id="foot">
		<li><%= link_to "Movies", movies_path %> </li>
		<li><%= link_to "Theatres", theatres_path %> </li>
		<li><%= link_to "Buddies", buddies_path %> </li>
		<li><%= link_to "Preferences", preferences_path %> </li>
		<li><%= link_to "AboutUs", "#" %> </li>
		<li><%= link_to "ContactUs", "#" %> </li>

</footer>
	<div id="copy-right">
		<p> Copyright © 2013 Easily Experience, Ltd. All original contents of this site including text, graphics, interfaces and design are designed by ifoondang.</p>
	</div>

app/views/layouts/_showtime.html.erb
<div id="quick-showtime">
	<div id="navigation-bar">
		<div id="left">
			<!--Main Menus-->
				<div id="movies-link" class="current" >
					<%= link_to "MOVIES" , root_path%>
				</div>
				<div id="movies-link" class="current" >
					<%= link_to "THEATRES" , theatres_path%>
				</div>
				<div id="movies-link" class="current" >
					<%= link_to "BUDDIES" , buddies_path%>
				</div>
				<!--Check if preferences page is on-->
				<%if @layout_type == "preferences"%>
					<div id="movies-link" class="current" >
						<%= link_to "TASTE PROFILE" , preferences_path%>
					</div>
				<%end%>
		</div>
			<!--
			<li role="navigation">
				<li class="dropdown">
					<a id="drop1" class="brand dropdown-toggle" href="#" role="button" data-toggle="dropdown">Flavu <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
						<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="http://blog.flavu.com/">Blog</a></li>
						<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="/contact">Contact</a></li>
						<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="aboutus">About Us</a></li>
					</ul>
				</li>
			</li>
			<li><%= link_to "News" , news_path%></li>

			<li><%= link_to "Showtimes" , showtimes_path%></li>
			<li><%= link_to "Trailers" , trailers_path%></li>
			

			<!--<li><%= link_to "Reviews" , reviews_path%></li>
			
			<li><%= link_to "Box Office" , boxoffice_path%></li>
			<%if cookies.signed['auth']%>
			<li>
				<%=form_tag '/buddies' ,:style=>"margin:0;" do%>
					<input id="request" name="request" type="text" placeholder="Send requests to your buddies">
					<button id="bt_find_friends" name="commit" class="icon-search" type="submit" title="Send requests to your buddies"></button>
				<%end%>
			</li>
			<%else%>
			<%end%>
			-->

			<!--
			<%if (!cookies.signed[:auth])%>
				<li>
		
					<a href="#myModal" data-toggle="modal" data-backdrop="true" class="title" >Log In</a>
					<div id="myModal" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
						<div class="modal-header">
		    				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		    				<h3 class="title">Log In</h3>
		    			</div>
		    			<div class="modal-body">
		    				<%if flash[:error]%><div class="alert"><%= flash[:error]%></div><%end%>
							<%= form_tag '/checklogin' ,:class=>"form-horizontal" do %>
						        <div class="control-group">
						          <label class="control-label" for="inputEmail">Login</label>
						          <div class="controls">    
						            <%= text_field_tag "login" ,nil,:placeholder=>"Username or Email"%>
						          </div>
						        </div>
						        <div class="control-group">
						          <label class="control-label" for="inputPassword">Password</label>
						          <div class="controls">    
						            <%= password_field_tag "password" ,nil,:placeholder=>"Password" %>
						          </div>
						        </div>
						        <div class="control-group">
						          <div class="controls">
						            <label class="checkbox">
						              <%=check_box("checkbox", "check")%>
						              Remember me
						            </label>
						            <button name="confirm" id="confirm" value="confirm" type="submit" class="btn"> Login </button>  
						          </div>  
						        </div>
						        <div class="control-group">
						          <div class="controls">
						          	<div id="forgot-password">
						          		<%=link_to "forgot password?", forgot_password_path%>
						          	</div>
						          </div>  
						        </div>
						    <%end%>
		  				</div>
					</div>
				</li>
				<li>
					<a href="/register" class="title">Register</a>
				</li>
			<%else%>

			<li class="dropdown">
				<a id="drop1" class="brand dropdown-toggle" href="#" role="button" data-toggle="dropdown">Your Welcome <%=cookies.signed['username']%> <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
					<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="/signout">Sign Out</a></li>
					<!--<%#if%>
					<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="/auth/facebook">Log in with Facebook</a></li>
					<%#else%>
					<%#end%>
					<%if !cookies.signed[:social_accounts]%>
					<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="/link_fb">Link to Facebook</a></li>
					<%else%>
					<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="/unlink_fb">Unlink from Facebook</a></li>
					<%end%>
				</ul>
			</li>
			<%end%>-->

			
			<!--Tabs-->
			
				
				<%if @layout_type == "movies"%>
				<ul class ="right">
					<li><a href="#interested" data-toggle="tab">
							Interested Movies
					</a></li>
					<li class="active"><a href="#remaining" data-toggle="tab">
							Remaining Movies
					</a></li>
					<li><a href="#not_interested" data-toggle="tab">
							Not Interested Movies
					</a></li>
					<li><a href="#watched_lists" data-toggle="tab">
							Watched Lists
					</a></li>
				</ul>
				<%elsif @layout_type == "theatres"%>
				<ul class ="right">
					<li><a href="#liked" data-toggle="tab">
							Liked
					</a></li>
					<li class="active"><a href="#nearby" data-toggle="tab">
							Nearby
					</a></li>
					<li><a href="#unliked_th" data-toggle="tab">
							Unliked
					</a></li>
				</ul>
				<%elsif @layout_type == "buddies"%>
				<ul class ="right">
					<li class="active"><a href="#movie_buddies" data-toggle="tab">
							Movie Buddies
					</a></li>
					<li><a href="#requests" data-toggle="tab">
							Requests(<%=@requests['total_entries']%>)
					</a></li>
					<li><a href="#friends" data-toggle="tab">
							Friends
					</a></li>
				</ul>
				<%elsif @layout_type == "preferences"%>
				<ul class ="right-taste">
					<div id="taste_profile_search">
						<%=form_tag '/search' do%>
							<input type="text" id="taste" name="taste" placeholder="search your taste">
							<button id="bt_search_taste" name="commit" class="icon-search" type="submit" ></button>
						<%end%>
					</div>
					
						<li class="active"><a href="#genres_p" data-toggle="tab">Genres</a></li>
						<li ><a href="#directors_p" data-toggle="tab">Directors</a></li>
						<li><a href="#actors_p" data-toggle="tab">Actors</a></li>
					<%end%>
				</ul>
	</div><!--navbar-inner-->
</div>

app/views/layouts/_side.html.erb
<div id="side">
		<div id="member">
			<h1> Flavu Member </h1>
			<div id="side-login-box">
			
<!--login-->
<%if flash[:error]%>
  <div class = "alert">
    <p> <%=flash[:error]%></p>
  </div>
<%else%>
<%end%>

  <%= form_tag '/checklogin' do %>
  <%if (!session[:auth])%>
  <div class="control-group">
    <div class="controls">
    	<div id="login-bar">
      <!--<label for="user_login">Login</label>-->
      <%= label_tag("Login") %>
      <!--<input id="user_login" name="user[login]" size="30" type="text">-->
      <%= text_field_tag "login"%>
      <!--<label for="user_password">Password</label>-->
      <%= label_tag("Password") %>

      <!--<input id="user_password" name="user[password]" size="30" type="password">-->
      <%= password_field_tag("password") %>

  		</div>
  		<div id="login-button">
  			<button name="confirm" id="confirm" value="confirm"> Login </button>
		</div>
		<div id="remember-but">
			<label>
	        	<input type="checkbox"> Remember me
	     	</label>
		</div>
    </div>
  </div>

	

 
  <%else%>
    <h11> Your Welcome <%=session['username']%></h11>
  <%end%>
<%end%>
<!--end of login-->


			</div>
		</div><!--member-->
	</div><!--side-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasilyxMovie</title>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "holder" %>
  <%= javascript_include_tag "bootstrap-transition" %>
  <%= javascript_include_tag "bootstrap-carousel" %>  
  <%= javascript_include_tag "bootstrap-modal" %>  
  <%= javascript_include_tag "bootstrap-tooltip" %> 
  <%= javascript_include_tag "bootstrap-popover" %>
  <%= javascript_include_tag "bootstrap-editable.min" %>
  <%= javascript_include_tag "geolocation" %>
  <%= javascript_include_tag "jquery_ujs" %>

  <%= stylesheet_link_tag    "bootstrap-editable.css", :media => "screen" %>

  <%= stylesheet_link_tag    "custom", :media => "screen" %>

  <%= csrf_meta_tags %>
	<!--Reponsive-->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="shortcut icon" href="/assets/Favicon.png" type="image/png">
	<!--Google Analytics-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41670747-1', 'flavu.com');
  ga('send', 'pageview');

</script>
  <%if @a1 && @guests %>
  <meta http-equiv="refresh" content="0; url=/cover"> 

<%else%>
<!--Hightlight the current page-->
<script>
$(function(){
	$('a').each(function() {
		if ($(this).prop('href') == window.location.href) {
			$(this).addClass('current');
		}
	});
});
</script>

</head>
<body>

<div id="wrapper">

	<header id="head">
		<!--
		<div id="search_bar" class="current"> 
			<%=form_tag '/buddy' do%>
			<div id="search_bar_text">
				<input id="search" name="search" type="text">
				<button id="bt_search" name="commit" class="icon-search" type="submit"></button>
			</div>

			<%end%>
		</div>-->
		<div id="mainnav">
				<ul id= "main-menu" class="menu">
					
					<li id="jewel " class="dropdown">
						<div id="jewel_container">
							<!--settings-->
							<div id="jewel_buddies">
								<a href="/settings">
									<p id="jp_c" class="icon-cog"></p>
								</a>
							</div>
							<!--Preferences-->
							<div id="jewel_profile">
								<a href="preferences">
									Taste Profile
								</a>
							</div>
							<!--							
							<div id="jewel_profile">
									<a id="drop1" class="brand dropdown-toggle" href="#" role="button" data-toggle="dropdown">Taste Profile</a>
									<ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
										<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="/preferences">Preferences</a></li>
										<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="/settings">Settings</a></li>
										<li id="dropdown1" role="presentation"><a role="menuitem" tabindex="-1" href="/signout">Sign Out</a></li>
									</ul>
							</div>
							-->
							<div id="jewel_notification">
								<p id="jp_c" class="icon-comment"></p>
							</div>
						</div>
					</li>
					<li id="gavatar">
						<img src="/assets/account_icon.png">
					</li>
				</ul>
		</div>
		<div id="logo">
			<img src="/assets/Flavu-Website-logo-200.png">
		</div>
		
		<div id="download-app">
			<a href="#"><img src="/assets/apple_store.png"></a>
		</div>
	</header>
			
</div>

<div class = "container">

	<!--Main Menu-->
	<%=render 'layouts/showtime'%>
		<div id="main" class="group" role="main">

			<%=yield%>

		</div>
	<%=render 'layouts/footer' %>

</div>


<%end%>

</body>
</html>

app/views/layouts/cover.html.erb
<html>
<head>
	  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "jquery_ujs" %>
<%= stylesheet_link_tag    "cover", :media => "all" %>
<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

</head>

<body>
<div class = "container">
	<div class="wrapper">
		<div id="header">
			<div id="logo">
				<img src="/assets/logof.png">
			</div>
			<div id="login-menu">
				<%if flash[:error]%>
					<div class = "alert">
				    	<p> <%=flash[:error]%></p>
				 	</div>
				<%else%>
				<%end%>
			</div>
		</div>
		<div class="content">
			<div id="cover-content">
				<%=form_tag '/cover' do %>
					<button class="btn btn-large" name="guest" id="guest" value="true"> Enter the website </button>
				<%end%>
				<div id="btn">
					<button data-target="#myModal" class="btn btn-large" name="guest" id="guest" value="true" data-toggle="modal" data-backdrop="true"> Log In </button>
					<div id="myModal" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
						<div class="modal-header">
				    		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				    		<h3 class="title">Log In</h3>
				    	</div>
				    	<div class="modal-body">
							<%= form_tag '/checklogin' do %>
								<div class="control-group">
									<div class="controls">
										<div id="login-bar">
											<%= label_tag("Login") %>
											<%= text_field_tag "login"%>
											<%= label_tag("Password") %>
											<%= password_field_tag("password") %>
										</div>
										<div id="login-button">
										  	<button name="confirm" id="confirm" value="confirm"> Login </button>
										</div>
										<div id="remember-but">
											<label>
											<%=check_box("checkbox", "check")%>
											Remember me</label>
										</div>
										<div id="forgot-password">
											<%=link_to "forgot password?", forgot_password_path%>
										</div>
									</div>
								</div>
							<%end%>
				  		</div>
					</div>
				</div>
				<div id="btn">
					<a href="/register"><button class="btn btn-large" name="guest" id="guest" value="true" > Register </button></a>

				</div>
			</div>
		</div>
	<%=yield%>
	</div>
</div>
</body>
</html>